### ISSUE TITLE
Plex for Web 4.94.2 Display Issues

### ISSUE THREAD

**Issue by ZeroFux78** [Balthier/Enhanced-Plex#25]
Hi, just installed this extension, but I don't think it's working. Nothing changed when I loaded Plex Web and looked at a tv show or movie.

**Comment by Balthier** [comment]
I'm actually using the same version, and things appear to be working as expected

Have you turned the different settings on in the Extension options?

<img width="194" alt="2022-11-20 16_14_41-EnhancedPLEX options" src="https://user-images.githubusercontent.com/9468615/202913120-d318bdb4-7df2-4eda-b8c1-89eb35c15e2d.png">

**Comment by Balthier** [comment]
Hi,

Just wondering if the above was helpful?

Thanks,
Balthier

**Comment by Balthier** [comment]
Closing due to no response
