### ISSUE TITLE
Option to run on local host

### ISSUE THREAD

**Issue by arogl** [Balthier/Enhanced-Plex#34]
Is there the possibility to allow the extension to run on localhost?

```
http://127.0.0.1:32400/web/index.html#!/
http://localhost:32400/web/index.html#!/
```

**Comment by Balthier** [comment]
Hi,

Last time I looked in to this, there were quite a few differences in the way Plex for Web, and the locally hosted Plex, are coded

I'll take another look in to this, since it's been a couple of years, but no guarantees at this point

Thanks,
Balthier

**Comment by arogl** [comment]
Thanks for looking.

**Comment by Balthier** [comment]
Hi,

I've made quite a few changes since I last looked a few years ago, but this is still going to require a little bit of work

I've got a couple of things to look at first, but I'll add this to the backlog as something that I will aim to include

Thanks,
Balthier

**Comment by Balthier** [comment]
I've added this to v3.1.0, which is likely to be released next month
