### ISSUE TITLE
Plex for Web Version 4.113.2 not tested/compatible

### ISSUE THREAD

**Issue by Germaenace** [Balthier/Enhanced-Plex#45]
I get following error message:
"EnhancedPlex Warning: Plex for Web version is 4.113.2 which is higher than the currently tested version: 4.110.1 - Please report any issues via the Known Issues link on the Options page"

Thanks for your great work and the many fixes/enhancements in last hours.
👍

![image](https://github.com/Balthier/Enhanced-Plex/assets/44316909/d1049cc7-6baf-452d-af91-97b2a87f1abd)

**Comment by Balthier** [comment]
Hi,

Thank you for raising this - I am actually currently in the process of testing a new version, against the latest Plex for Web version :)

Hopefully, it should be released and approved this weekend

Thanks,
Balthier
