### ISSUE TITLE
Stats failed to fetch

### ISSUE THREAD

**Issue by Californ1a** [Balthier/Enhanced-Plex#71]
If your plex server is only set up to be used in your internal network, or for any other reason you have "Not available outside your network" in the [Remote Access](https://support.plex.tv/articles/200289506-remote-access/) settings, then the external `[ip/id].plex.direct:20307/library/sections/?X-Plex-Token=` url the stats page tries to fetch from will fail and the stats page will just be permanently darkened/loading.

Could there be an option to use an internal address like `127.0.0.1:32400/library/sections/`, `10.0.0.75:32400/library/sections/`, or `192.168.0.75:32400/library/sections/` to fetch the stats?

**Comment by Balthier** [comment]
From the face of it, seems possible - I'll take a look this week

**Comment by Californ1a** [comment]
![](https://i.imgur.com/tM7CfGA.png)

Same also happens within plex on show pages as well, anything using the getXML function when plex.direct is unaccessible:
![](https://i.imgur.com/yqj5lVY.png)
(btw, `Show Tokens` toggled off doesn't hide the token in the `getPlexToken` debug log)

**Comment by Balthier** [comment]
Ok, I'll see if I can get an installation configured for this specific issue, to help me replicate/test

I've created a second issue for the getPlexToken

**Comment by Californ1a** [comment]
There's a few potential automated solutions that might work without needing the user to config a separate option, like keep an entry in storage for what host address to use for fetching, and if it's empty, check `document.location.host` on plex pages before fetching to see if it's localhost or a local ip, then try fetching from there instead, and if it works, save that address so it can also be used from the stats page. If it fails then fallback to plex.direct. An override option to manually config the address would be nice to have though, but probably better for less advanced users if it can at least attempt to automatically find the right address.

**Comment by Balthier** [comment]
Yeah, there is already the information that is pulled fairly early in the extension, it just isn't stored at the minute, since the uri/plex.direct link is already presented in the correct format - Should be able to build the local link with the additional info in the xml

**Comment by Balthier** [comment]
Made some changes to the URI selection process:

Local (Direct, HTTPS) -> Local (Plex Proxy) -> Local (Direct, HTTP)

I still haven't been able to reproduce the issue, but hopefully, this new selection process covers a variety of scenarios.
