### ISSUE TITLE
'Missing Content' doesn't work properly with named seasons

### ISSUE THREAD

**Issue by Californ1a** [Balthier/Enhanced-Plex#74]
If you have season titles enabled (under Manage library->Edit->Advanced->Use season titles), missing content doesn't get added in the correct location, the 'x/total' episode counts aren't displayed on existing seasons, and the seasons that do exist get reordered incorrectly:
![](https://i.imgur.com/oiyZ8wB.png)
![](https://i.imgur.com/W19hXW8.png)

With missing content disabled:
![](https://i.imgur.com/5WJt76r.png)
![](https://i.imgur.com/F8jq4o9.png)

![](https://i.imgur.com/6AJtNko.png)

**Comment by Balthier** [comment]
I can reproduce this one - It's a bit more of an awkward fix, so will likely take a little longer
